spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: false
  application:
    name: Team-10-Manage-User
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:file:./data/mydb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.sau-portal.de/realms/sau
          jwk-set-uri: https://keycloak.sau-portal.de/realms/sau/protocol/openid-connect/certs

keycloak:
  serverUrl: https://keycloak.sau-portal.de
  realm: sau
  clientId: ${KC_CLIENT_ID}
  clientSecret: ${KC_CLIENT_SECRET}
server:
  port: 8080
  servlet:
    context-path: /userapi
  error:
    include-message: always
