apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-api-app
  template:
    metadata:
      labels:
        app: user-api-app
    spec:
      containers:
        - name: user-api-container
          image: ghcr.io/agile-software-engineering-25/team-10-userapiservice:latest
          command: ["java", "-jar", "app.jar"]
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "1024Mi"
              cpu: "1000m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          # livenessProbe:
          #   httpGet:
          #     path: /demo
          #     port: 8080
          #   initialDelaySeconds: 12
          #   periodSeconds: 10
          env:
            - name: KC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: api-wrapper
                  key: KC_USERNAME
            - name: KC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-wrapper
                  key: KC_PASSWORD
            - name: BITFROST_PROJECT_SECRET
              valueFrom:
                  secretKeyRef:
                    name: api-wrapper
                    key: BITFROST_PROJECT_SECRET

